blank_issues_enabled: false
# contact_links:
#   - name: <PROJECT_FULLNAME> documentation
#     url: https://domain.com/
#     about: Check out the <PROJECT_FULLNAME> documentation for answers to common questions.
